Senzing/senzing-up

senzing-up.sh
=> Issue 3.dockter.3

README.md, senzing-up.sh
=> Issue 3.dockter.4

README.md
=> #3 Download of raw file

README.md, senzing-up.sh
=> Issue 3.dockter.6

README.md, senzing-up.sh
=> Issue 3.dockter.7

senzing-up.sh
=> #3 Add Senzing API server port

CHANGELOG.md, senzing-up.sh
=> #15 Fixed appending to history.log

CHANGELOG.md
=> #17 Fix version

README.md, docs/README.md, docs/tutorial.md, senzing-up.sh
=> Issue 21.dockter.1

CHANGELOG.md, README.md, docs/advanced.md, docs/tutorial.md, senzing-up.sh
=> Issue 23.dockter.1

docs/advanced.md
=> #26 Add information for databases

senzing-up.sh
=> #26 Add elevated permissions

docs/advanced.md
=> #26  Fix order of instructions

CHANGELOG.md
=> #26 Prepare for version

senzing-up.sh
=> #34 Added SCRIPT_VERSION

CHANGELOG.md
=> #34 Prepare for versioned release

docs/tutorial.md
=> Issue 38.dockter.1

CHANGELOG.md, senzing-up.sh
=> Issue 45.dockter.1

senzing-up.sh
=> #45 Migrate from data 1.0.0 to 2.0.0

.github/CODEOWNERS, CHANGELOG.md, senzing-up.sh
=> Issue 48.dockter.1

README.md
=> #57 add README changes for deprecation
